---
driver:
  name: ec2
  aws_ssh_key_id: KeyName # key pair name
  region: us-east-1 # region code of aws
  availability_zone: us-east-1a # availability_zone of us-west
#  subnet_id: subnet-89fb32ee # subnet-id noted from above steps
  instance_type: t2.micro # as it is free instance type
  image_id: ami-0565af6e282977273 # image id of ubuntu
#  security_group_ids: ["sg-0caf47d86b61769cb"]
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
transport:
  ssh_key: C:\Users\Teja\Downloads\Compressed\chef-repo\cookbooks\new_lamp\KeyName.pem # relative path to pem file
  username: ubuntu # username from ami-id

platforms:
  - name: ubuntu-16.04
#  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[new_lamp::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
